#!/bin/zsh

# Custom Prompt
# I'm keeping this one line and relatively short
# %n    is your username
# %m    is your machine name (abbreviated)
# %~    is your current directory (abbreviated with `~` for `HOME`)
# %#    is a "prompt character" (% for a regular user, # for a superuser)
# For preview, you can use this
# print -P '%F{green}%n@%m%f %F{blue}%~%f %# '

# L_BRACKET
# running w/ priveleges or not and name
# machine
# directories
# R_BRACKET
# dollar sign w/ color based on exit status
PS1="%B%F{blue}[%f%b\
%F{yellow}%#%n%f\
%F{magenta}@%m%f \
%10<..<%~%<<\
%B%F{blue}]%f%b\
%F{%(?.green.red)}$%f "

if [ -f ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/git-prompt.sh ]; then
    source ${XDG_CONFIG_HOME:-$HOME/.config}/zsh/git-prompt.sh
    export GIT_PS1_SHOWDIRTYSTATE=1     # unstaged (*) staged (+)
    export GIT_PS1_SHOWSTASHSTATE=1     # stash symbol ($)
    export GIT_PS1_SHOWUNTRACKEDFILES=1 # untracked (%)
    export GIT_PS1_SHOWCOLORHINTS=1
    export GIT_PS1_SHOWCONFLICTSTATE="yes"
    setopt PROMPT_SUBST
    RPROMPT='$(__git_ps1 "(%s)")'
fi

