#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkdir="mkdir -pv" \
    src="source $HOME/.config/zsh/.zshrc" \
    iv="sxiv -a" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner" \
    convert="magick convert -verbose" \
    weather="curl wttr.in" \
    df="df -h" \
    trp="trash-put" \
    trl="trash-list" \
    trr="trash-restore" \
    sx="startx"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto"
    # ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura" \
    wget="wget --hsts-file=\"$XDG_DATA_HOME/wget-hsts\"" \
    g="git" \
    ff="firefox" \
    pn="pnpm" \
    xdg-qf="xdg-mime query filetype" \
    xdg-qd="xdg-mime query default" \
    xdg-def="xdg-mime default" \
    spotdl="spotdl --config" \
    rime-i="rime_dir="$XDG_DATA_HOME/.config/fcitx5/rime" bash ~/Downloads/plum/rime-install" \
    tmux-src="tmux source $XDG_CONFIG_HOME/tmux/tmux.conf"

