#!/bin/sh

mkcd() { mkdir -pv "$1" && cd "$1" }
mvcd() { mv -vi "$1" "$2" && cd "$2" }

fcd() {
    case $1 in
        "c" ) cd $(find "$HOME/.config/" -type d | fzf) ;;
        "sc") cd $(find "$HOME/.local/bin/" -type d | fzf) ;;

        "dl") cd "$HOME/Downloads/" ;;
        "ss") cd "$HOME/Pictures/screenshots/" ;;
        "w" ) cd $(find "$HOME/Pictures/wallpapers/" -type d | fzf) ;;
        "m" ) cd $(find "$HOME/Music/" -type d | fzf) ;;
        "d" ) cd $(find "$HOME/Documents/" -type d | fzf) ;;
        *   ) cd $(find ${1:-"$HOME"} -type d >/dev/null 2>&1 | fzf) ;;
    esac
}

open() {
    case $1 in
        "doc") xdg-open $(find "$HOME/Documents/"   -type f | fzf) ;;
        "dl" ) xdg-open $(find "$HOME/Downloads/"   -type f | fzf) ;;
        "m"  ) xdg-open $(find "$HOME/Music/"       -type f | fzf) ;;
        "p"  ) xdg-open $(find "$HOME/Pictures/"    -type f | fzf) ;;
        *    ) xdg-open $(find ${1:-"$HOME"}   -type f >/dev/null 2>&1 | fzf) ;;
    esac
}

getpath() { find ${1:-"$HOME"} -type f | fzf | tr -d '\n' | xclip -selection c }

