#!/bin/sh

mkcd() { mkdir -pv "$1" && cd "$1" }
mvcd() { mv -vi "$1" "$2" && cd "$2" }

fcd() {
    case ${1:-"$HOME"} in
        "c"  ) cd $(find "$HOME/.config/" -type d | fzf) ;;
        "s"  ) cd "$HOME/.config/shell" ;;
        "v"  ) cd "$HOME/.config/nvim/" ;;
        "x"  ) cd "$HOME/.config/X11/"  ;;
        "z"  ) cd "$HOME/.config/zsh/"  ;;
        "scr") cd $(find "$HOME/.local/bin/" -type d | fzf) ;;

        "dl" ) cd "$HOME/Downloads/" ;;
        "ss" ) cd "$HOME/Pictures/screenshots/" ;;
        "wl" ) cd "$HOME/Pictures/wallpapers/"  ;;
        "p"  ) cd $(find "$HOME/Pictures/"  -type d | fzf) ;;
        "m"  ) cd $(find "$HOME/Music/"     -type d | fzf) ;;
        "doc") cd $(find "$HOME/Documents/" -type d | fzf) ;;
        *    ) cd $(find "$p" -type d >/dev/null 2>&1 | fzf) ;;
    esac
    case ${2:-""} in
        "v") nvim . ;;
        "l") ls -lAh ;;
    esac
}

open() {
    local p=${1:-"$HOME"}
    case $p in
        "doc") xdg-open $(find "$HOME/Documents/"   -type f | fzf) ;;
        "dl" ) xdg-open $(find "$HOME/Downloads/"   -type f | fzf) ;;
        "m"  ) xdg-open $(find "$HOME/Music/"       -type f | fzf) ;;
        "p"  ) xdg-open $(find "$HOME/Pictures/"    -type f | fzf) ;;
        *    ) xdg-open $(find $p   -type f >/dev/null 2>&1 | fzf) ;;
    esac
}

getpath() { local p=${1:-"$HOME"} ; find $p -type f | fzf | tr -d '\n' | xclip -selection c }

