#!/bin/sh

mkcd() { mkdir -pv "$1" && cd "$1" || exit; }
mvcd() { mv -vi "$1" "$2" && cd "$2" || exit; }

nobloat_find() {
    find "$1" -not \( -wholename "*/.git" -prune \) \
        -not \( -wholename "*/node_modules" -prune \) \
        -type "$2" 2>/dev/null
}

general_find() {
    case $1 in
        "c"  ) nobloat_find "$HOME/.config/"      "${2:-d}" | fzf ;;
        "bi" ) nobloat_find "$HOME/.local/bin/"   "${2:-d}" | fzf ;;
        "sh" ) nobloat_find "$HOME/.local/share/" "${2:-d}" | fzf ;;

        "d"  ) nobloat_find "$HOME/Documents/"                  "${2:-d}" | fzf ;;
        "dks") nobloat_find "$HOME/Documents/kuliah/semester/"  "${2:-d}" | fzf ;;
        "dko") nobloat_find "$HOME/Documents/kuliah/ospek/"     "${2:-d}" | fzf ;;
        "dv" ) nobloat_find "$HOME/Documents/dev/"              "${2:-d}" | fzf ;;
        "db" ) nobloat_find "$HOME/Documents/buku/"             "${2:-d}" | fzf ;;

        "pw" ) nobloat_find "$HOME/Pictures/wallpapers/"    "${2:-d}" | fzf ;;
        "pp" ) nobloat_find "$HOME/Pictures/myphone/"       "${2:-d}" | fzf ;;

        "dl" ) nobloat_find "$HOME/Downloads/"  "${2:-d}" | fzf ;;
        "m"  ) nobloat_find "$HOME/Music/"      "${2:-d}" | fzf ;;
        "v"  ) nobloat_find "$HOME/Videos/"     "${2:-d}" | fzf ;;
        *    ) nobloat_find "$1"                "${2:-d}" | fzf ;;
    esac
}

fcd() {
    cd "$(general_find "$1" )" || exit
}

open() {
    xdg-open "$(general_find "${1:-d}" "f" )"
}

gfp() {
    general_find "$1" "f" | tr -d '\n' | xclip -selection c
}

gdp() {
    general_find "$1" "d" | tr -d '\n' | xclip -selection c
}

pms() {
    pacman -Ssq "$1" | fzf --multi --preview 'pacman -Si {1}; pacman -Qi {1}' | xargs -ro sudo pacman -S
}

pmr() {
    pacman -Ssq "$1" | fzf --multi --preview 'pacman -Si {1}; pacman -Qi {1}' | xargs -ro sudo pacman -Rns
}

pmq() {
    pacman -Qsq "$1" | fzf --multi --preview 'pacman -Qi {1}; pacman -Qo {1}' | xargs -ro pacman -Qi
}

img_shuf() {
    find . -name '*' -exec file {} \; | grep -o -P '^.+: \w+ image' | awk '{gsub(":",""); print $1}'
}

simple_countdown() {
    for i in $(seq "${1:-10}" -1 1) ; do
        clear ; figlet "$i" ; sleep 1
    done
    clear ; figlet STOP
}

