n       script-binding chapters/add_chapter
ctrl+m  script-binding chapters/remove_chapter
ctrl+.  script-binding chapters/edit_chapter
N       script-binding chapters/write_chapters
ctrl+,  script-binding chapters/bake_chapters

t       script-message-to seek_to toggle-seeker
