#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Set CAPS key=ESC|CTRL and CTRL key=SUPER
setxkbmap -layout "us,us" -variant "dvp," -option "ctrl:swapcaps,grp:win_space_toggle,compose:ralt"
xmodmap -e "keycode 37 = Super_L"   # My super key is physically broken
xmodmap -e "clear lock"             # Remove capslock
xcape -e "Control_L=Escape"         # Turn capslock to ESC when pressed alone

# Always use nvidia to render bc 490 driver cannot do hybrid *sadge*
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96

autostart="fcitx5 mpd mpd-mpris unclutter sxhkd slstatus"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

xrdb "${XDG_CONFIG_HOME:-$HOME/.config}"/X11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
setwp .
xautolock -time 15 -locker slock &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
while :; do
	ssh-agent dwm
done
