#!/bin/sh

export MESA_LOADER_DRIVER_OVERRIDE=iris # for intel gen 8
# https://wiki.alpinelinux.org/wiki/BusyBox

# Default programs
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="foot"
export BROWSER="librewolf"
export PAGER="nvim +Man!"
export MANPAGER="nvim +Man!"

# xdg base dirs
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XCOMPOSEFILE="$XDG_CONFIG_HOME"/X11/xcompose
export XCOMPOSECACHE="$XDG_CACHE_HOME"/X11/xcompose

# Clean up

# ANDROID SDK ENVIRONMENT VARIABLES https://developer.android.com/tools/variables
export ANDROID_HOME="$XDG_DATA_HOME/android"
export ANDROID_USER_HOME="$XDG_DATA_HOME/android"
export ANDROID_SDK_HOME="$XDG_DATA_HOME/android"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME}/ansible/ansible.cfg"
export ANSIBLE_GALAXY_CACHE_DIR="${XDG_CACHE_HOME}/ansible/galaxy_cache"
# If using zsh
# export ZDOTDIR="$XDG_CONFIG_HOME/zsh/"
# export HISTFILE="$XDG_STATE_HOME/zsh/history"
export HISTFILE="$XDG_STATE_HOME/history"
export HISTSIZE=5000
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
export LESSHISTFILE="$XDG_STATE_HOME/less/history"
export GOPATH="$XDG_STATE_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export PYTHONSTARTUP="/etc/python/pythonrc"
export R_HOME_USER="$XDG_CONFIG_HOME/R"
export R_PROFULE_USER="$XDG_CONFIG_HOME/R/profile"
export R_HISTFILE="$XDG_CONFIG_HOME/R/history"
export PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"
export TEXMFHOME="$XDG_DATA_HOME/texmf"
export TEXMFVAR="$XDG_CACHE_HOME/texlive/texmf-var"
export TEXMFCONFIG="$XDG_CONFIG_HOME/texlive/texmf-config"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CHROME_EXECUTABLE="/usr/bin/chromium"
# export SDL_DYNAMIC_API=/usr/lib64/libSDL2-2.0.so.0
export SDL_VIDEODRIVER=wayland
# export PIPEWIRE_DEBUG=3

# pnpm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PNPM_HOME="/home/nggeng/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--reverse --color fg:-1,bg:-1,hl:230,fg+:3,bg+:233,hl+:229 \
--color info:150,prompt:110,spinner:150,pointer:167,marker:174 \
--bind \"ctrl-y:replace-query\" \
"
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history

# IME
# export GTK_IM_MODULE="wayland"
export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export QT_IM_MODULE=fcitx

export PATH="/usr/local/texlive/2024/bin/x86_64-linuxmusl:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/usr/local/bin:/usr/sbin:/sbin"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/.local/share/cargo/bin"
export PATH="$PATH:$HOME/.config/composer/vendor/bin"
export PATH="/usr/bin/flutter/bin:$PATH"
export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"

if [ -z "$XDG_RUNTIME_DIR" ]; then
    XDG_RUNTIME_DIR="/tmp/$(id -u)-runtime-dir"
    mkdir -pm 0700 "$XDG_RUNTIME_DIR"
    export XDG_RUNTIME_DIR
fi

# WAYLAND
# https://codeberg.org/dwl/dwl/issues/629
# https://codeberg.org/korei999/dwl/src/branch/main/dwl-start
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway # sway because this makes obs screen sharing work
export XDG_SESSION_DESKTOP=sway

export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORMTHEME=qt5ct

export JAVA_HOME=/usr/lib/jvm/java-11-openjdk
export _JAVA_AWT_WM_NONREPARENTING=1
export CLUTTER_BACKEND="wayland"
export SDL_VIDEODRIVER="wayland,x11"

export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland

export LADSPA_PATH="$HOME/.local/share/ladspa:/usr/lib/ladspa:/usr/local/lib/ladspa"

export ENV="$HOME/.config/ash/ashrc"
